# Generated by Django 4.2.6 on 2023-10-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Accounting_Period', models.CharField(max_length=100)),
                ('Scope1', models.IntegerField(null=True)),
                ('Scope2', models.IntegerField(null=True)),
                ('Scope3', models.IntegerField(null=True)),
            ],
        ),
    ]
