# Generated by Django 4.2.6 on 2023-10-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emissions',
            new_name='Emission',
        ),
    ]
